### ISSUE TITLE
2. dub-sar 3. ... problem

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_cdli_ur3_corpus#2]
Hi,
I don't know what happened when you processed the ATF but some new lines were removed and it breaks the text.

Look for example at

https://github.com/cdli-gh/mtaac_cdli_ur3_corpus/blob/master/ur3_corpus_data/atf/P100435.atf

Now in all atf and conll: https://github.com/search?utf8=%E2%9C%93&q=org%3Acdli-gh+dub-sar3.&type=Code

**Comment by epageperron** [comment]
@khoidt @wangj619

**Comment by epageperron** [comment]
Another one: 
https://github.com/cdli-gh/mtaac_cdli_ur3_corpus/blob/master/ur3_corpus_data/atf/P101347.atf

**Comment by khoidt** [comment]
@epageperron, it's great that you noticed this!
It seems that the problem has to do with `lxml.html.text_content()` unexpectedly ignoring `br` inside CDLI's `del` tag. I hope to find a solution soon, then I'll update all texts.

**Comment by epageperron** [comment]
I'm not sure I follow, what is a "del" tag? by br you mean new line? I have never seen a `<br>` in ATF? Am I understanding you are scaping the website? Why?

**Comment by epageperron** [comment]
the del tag in the version history ? ...

**Comment by khoidt** [comment]
Yes, my script takes the ATF from CDLI's version history. It's fixed now, and the new ATF data is there, so I will update the files here and in to_annotate in the next few hours.

**Comment by epageperron** [comment]
Thanks for the explanation and the fix !!
